### ISSUE TITLE
Autocomplete not working for me

### ISSUE THREAD

**Issue by johtso** [mattpocock/vscode-xstate-demo#3] opened 2021-07-14 20:16 UTC
Not entirely sure how to get to the bottom of this.

The extension is correctly telling me that the state doesn't exist as I type, I just don't get any autocomplete suggestions.

Tried disabling all extensions except this one and same behavior.

https://user-images.githubusercontent.com/830800/125686581-9ccd1375-4788-40a7-9ae6-1dc7bc20b10a.mov

**Comment by johtso** [comment] 2021-07-14 21:01
Aha, so seems that by default "quick suggestions" are disabled in strings. Need to change this setting:

```json
  "editor.quickSuggestions": {
    "other": true,
    "strings": true,
    "comments": true
  }
```

**Comment by mattpocock** [comment] 2021-07-16 07:37
The issue is that VSCode doesn't appear to provide a great way to _initiate_ autocompletions based on the location of your cursor. It does it whenever you type a `.`, and I can add to these 'trigger characters'. But since targets can be arbitrarily named, anything could be a trigger character - meaning autocomplete would trigger throughout the file no matter what you typed.

**Comment by mattpocock** [comment] 2021-09-11 22:36
Closing

**Closed by mattpocock** 2021-09-11 22:36 UTC

**Comment by Enteleform** [comment] 2021-09-22 04:06
> The issue is that VSCode doesn't appear to provide a great way to _initiate_ autocompletions based on the location of your cursor.

![image](https://user-images.githubusercontent.com/10906415/134281771-f1ffd59b-ebba-4e9c-b3d2-845e47a33d71.png)

**Comment by mattpocock** [comment] 2021-09-22 06:55
Yep, that's what I use.
